
include("repotree.jl")
include("find.jl")
include("git_pull.jl")
include("git_commit.jl")
include("git_add_all.jl")
include("git_push.jl")
include("git_tracked.jl")
include("git_staged.jl")
include("git_head_hash.jl")
include("git_get_origin_url.jl")
